### ISSUE TITLE
Support Eclipse 2020-03

### ISSUE THREAD

**Issue by broomyocymru** [DecisionsDev/ruledesigner#9]
Unable to add rules designer to latest version of eclipse. Is there any plans to support newer versions?

**Comment by michjk** [comment]
+1 appreciate if there are plans to support new eclipse.

**Comment by lgrateau** [comment]
Let check with the marketing team.

**Comment by broomyocymru** [comment]
Hi, any update on this?

**Comment by ebonnet31** [comment]
Hi guys,
I am adding a +1 on this one as one of my customer wants to use ODM with JDK 11 and Eclipse minimum version for JDK 11 is 2018-12 (4.10).

**Comment by lomagnin** [comment]
In some places we don't have choice over the Eclipse version we can use. And/or we need a specific version because of required extra features & plugins. Therefore, having no freedom on the supported Eclipse versions might be in some cases an unfortunate no go for ODM...

Q: are those restrictive required versions of Eclipse come from incompatibilities or by lack of testing?

**Comment by nrankovic** [comment]
Hi everyone. Is there an update about this issue? 

After upgrading to MacOS 11 Big Sur, Eclipse Oxygen, Photon and Luna are crashing, not stable, and only plugins available for Rule Designer are for those versions. This makes it impossible to use ODM on new MacOS.

**Comment by smartheye** [comment]
+1 

eclipse 4.7 is no more working on MacOS 11 Big Sur.
please update the plugin align with latest eclipse .

**Comment by dbajamdecisions** [comment]
the team is working on this follow https://dba.ideas.aha.io/ideas/ADS-I-73

**Comment by tourl** [comment]
+1

any news on this?

**Comment by lgrateau** [comment]
closing it too old
